channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy=1.10.1
  - pysam=0.22.1
  - Cigar=0.1.3
  - numpy=1.24.4
  - biopython=1.83
  - scikit-learn=1.3.2
  - cython=3.0.11
  - minimap2=2.28
  - samtools=1.21
  - pip
  - watchdog=4.0.1
  - pip:
      - pyvcf3==1.0.3
